### ISSUE TITLE
Adding hit animal bonus for agressor on defined zone

### ISSUE THREAD

**Issue by Jim1120** [daemonforge/Dayz-HeroesAndBandits#9]
Hi Daemon !

Can you edit your AnimalBase.c and Actions.json for adding hit animal bonus for agressor on defined zone because some place are many wolf or bear spawn arround zone and the friendly cleaning zone get agressor point.

I edit like that for save time : 
AnimalBase.c
https://hastebin.com/vupuxehaya.cpp

Actions.json : 
`        {
            "Name": "HitAnimal",
            "Amount": -60.0
        },
`

On Loader and Converter : 
`AggressorActions.Insert( new ref habAggressorAction("HitAnimal", -60));`

Thank you 👍

**Comment by DaemonF0rge** [comment]
Pushed a fix to experimental, will release to stable on next stable update
